name: Cypress Tests and Heroku Deployment

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          # Set up Heroku git remote
           git remote add heroku https://heroku:${{ secrets.HEROKU_API_KEY }}@git.heroku.com/tddah-fe.git

          # Push changes to Heroku
          git push heroku main
