name: Cypress Tests and Heroku Deployment

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Deploy to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          # Login to Heroku
          heroku login -i

          # Set up Heroku git remote
          heroku git:remote -a tddah-fe

          # Push changes to Heroku
          git push heroku HEAD:main
