name: Cypress Tests

on: [push]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    environment: Test
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5.5.1 # use the explicit version number
        with:
          build: npm run build
          start: npm start

      # Add a step to deploy to Heroku
      - name: Deploy to Heroku
        run: |
          # Login to Heroku
          heroku login -i

          # Add Heroku remote to the git repository
          heroku git:remote -a your-heroku-app-name

          # Push the changes to Heroku remote
          git push heroku HEAD:main